# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-02 02:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=20, verbose_name='\u4efb\u52a1ID')),
                ('task_name', models.CharField(max_length=50, verbose_name='\u4efb\u52a1\u540d')),
                ('start_ip', models.CharField(max_length=39, verbose_name='\u8d77\u59cbIP')),
                ('end_ip', models.CharField(max_length=39, verbose_name='\u4e2d\u6b62IP')),
                ('result', models.CharField(choices=[('\u68c0\u6d4b\u6210\u529f', 'true'), ('\u68c0\u6d4b\u5931\u8d25', 'false')], max_length=5)),
                ('message', models.TextField(verbose_name='\u5176\u4ed6\u4fe1\u606f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1',
                'verbose_name_plural': '\u4efb\u52a1',
            },
        ),
    ]
