# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-02 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.CharField(choices=[('true', '\u68c0\u6d4b\u6210\u529f'), ('false', '\u68c0\u6d4b\u5931\u8d25')], max_length=5),
        ),
    ]
